version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pg-dev
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_DATABASE: mydb
      NODE_ENV: development
    volumes:
      - .:/app
      - /node_modules
      - /dist
    command: npm run start:dev
volumes:
  postgres_data: